arcana2Combos = [
    {'source': ['Fool',       'Fool'        ], 'result': 'Fool'        },
    {'source': ['Fool',       'Magician'    ], 'result': 'Hierophant'  },
    {'source': ['Fool',       'Priestess'   ], 'result': 'Justice'     },
    {'source': ['Fool',       'Empress'     ], 'result': 'Fortune'     },
    {'source': ['Fool',       'Emperor'     ], 'result': 'Chariot'     },
    {'source': ['Fool',       'Hierophant'  ], 'result': 'Hermit'      },
    {'source': ['Fool',       'Lovers'      ], 'result': 'Priestess'   },
    {'source': ['Fool',       'Chariot'     ], 'result': 'Emperor'     },
    {'source': ['Fool',       'Justice'     ], 'result': 'Lovers'      },
    {'source': ['Fool',       'Hermit'      ], 'result': 'Priestess'   },
    {'source': ['Fool',       'Fortune'     ], 'result': 'Justice'     },
    {'source': ['Fool',       'Strength'    ], 'result': 'Hanged Man'  },
    {'source': ['Fool',       'Hanged Man'  ], 'result': 'Magician'    },
    {'source': ['Fool',       'Death'       ], 'result': 'Strength'    },
    {'source': ['Fool',       'Temperance'  ], 'result': 'Hierophant'  },
    {'source': ['Fool',       'Devil'       ], 'result': 'Hermit'      },
    {'source': ['Fool',       'Tower'       ], 'result': 'Moon'        },
    {'source': ['Fool',       'Star'        ], 'result': 'Aeon'        },
    {'source': ['Fool',       'Moon'        ], 'result': 'Fortune'     },
    {'source': ['Fool',       'Sun'         ], 'result': 'Empress'     },
    {'source': ['Fool',       'Judgment'    ], 'result': 'Star'        },
    {'source': ['Fool',       'Aeon'        ], 'result': 'Death'       },
    {'source': ['Magician',   'Magician'    ], 'result': 'Magician'    },
    {'source': ['Magician',   'Priestess'   ], 'result': 'Lovers'      },
    {'source': ['Magician',   'Empress'     ], 'result': 'Hanged Man'  },
    {'source': ['Magician',   'Emperor'     ], 'result': 'Temperance'  },
    {'source': ['Magician',   'Hierophant'  ], 'result': 'Hermit'      },
    {'source': ['Magician',   'Lovers'      ], 'result': 'Emperor'     },
    {'source': ['Magician',   'Chariot'     ], 'result': 'Devil'       },
    {'source': ['Magician',   'Justice'     ], 'result': 'Hierophant'  },
    {'source': ['Magician',   'Hermit'      ], 'result': 'Chariot'     },
    {'source': ['Magician',   'Fortune'     ], 'result': 'Emperor'     },
    {'source': ['Magician',   'Hanged Man'  ], 'result': 'Devil'       },
    {'source': ['Magician',   'Temperance'  ], 'result': 'Death'       },
    {'source': ['Magician',   'Devil'       ], 'result': 'Temperance'  },
    {'source': ['Magician',   'Tower'       ], 'result': 'Empress'     },
    {'source': ['Magician',   'Star'        ], 'result': 'Empress'     },
    {'source': ['Magician',   'Moon'        ], 'result': 'Priestess'   },
    {'source': ['Magician',   'Sun'         ], 'result': 'Lovers'      },
    {'source': ['Priestess',  'Priestess'   ], 'result': 'Priestess'   },
    {'source': ['Priestess',  'Empress'     ], 'result': 'Lovers'      },
    {'source': ['Priestess',  'Emperor'     ], 'result': 'Justice'     },
    {'source': ['Priestess',  'Hierophant'  ], 'result': 'Chariot'     },
    {'source': ['Priestess',  'Lovers'      ], 'result': 'Magician'    },
    {'source': ['Priestess',  'Chariot'     ], 'result': 'Magician'    },
    {'source': ['Priestess',  'Justice'     ], 'result': 'Lovers'      },
    {'source': ['Priestess',  'Hermit'      ], 'result': 'Strength'    },
    {'source': ['Priestess',  'Fortune'     ], 'result': 'Magician'    },
    {'source': ['Priestess',  'Strength'    ], 'result': 'Hermit'      },
    {'source': ['Priestess',  'Hanged Man'  ], 'result': 'Strength'    },
    {'source': ['Priestess',  'Death'       ], 'result': 'Emperor'     },
    {'source': ['Priestess',  'Temperance'  ], 'result': 'Empress'     },
    {'source': ['Priestess',  'Star'        ], 'result': 'Justice'     },
    {'source': ['Priestess',  'Moon'        ], 'result': 'Star'        },
    {'source': ['Priestess',  'Sun'         ], 'result': 'Star'        },
    {'source': ['Priestess',  'Judgment'    ], 'result': 'Empress'     },
    {'source': ['Priestess',  'Aeon'        ], 'result': 'Empress'     },
    {'source': ['Empress',    'Empress'     ], 'result': 'Empress'     },
    {'source': ['Empress',    'Emperor'     ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Hierophant'  ], 'result': 'Priestess'   },
    {'source': ['Empress',    'Lovers'      ], 'result': 'Fortune'     },
    {'source': ['Empress',    'Chariot'     ], 'result': 'Devil'       },
    {'source': ['Empress',    'Justice'     ], 'result': 'Emperor'     },
    {'source': ['Empress',    'Hermit'      ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Fortune'     ], 'result': 'Strength'    },
    {'source': ['Empress',    'Strength'    ], 'result': 'Chariot'     },
    {'source': ['Empress',    'Hanged Man'  ], 'result': 'Chariot'     },
    {'source': ['Empress',    'Death'       ], 'result': 'Devil'       },
    {'source': ['Empress',    'Temperance'  ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Devil'       ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Tower'       ], 'result': 'Chariot'     },
    {'source': ['Empress',    'Star'        ], 'result': 'Temperance'  },
    {'source': ['Empress',    'Moon'        ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Sun'         ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Aeon'        ], 'result': 'Moon'        },
    {'source': ['Emperor',    'Emperor'     ], 'result': 'Emperor'     },
    {'source': ['Emperor',    'Hierophant'  ], 'result': 'Chariot'     },
    {'source': ['Emperor',    'Lovers'      ], 'result': 'Chariot'     },
    {'source': ['Emperor',    'Chariot'     ], 'result': 'Hermit'      },
    {'source': ['Emperor',    'Justice'     ], 'result': 'Devil'       },
    {'source': ['Emperor',    'Hermit'      ], 'result': 'Strength'    },
    {'source': ['Emperor',    'Strength'    ], 'result': 'Hanged Man'  },
    {'source': ['Emperor',    'Hanged Man'  ], 'result': 'Hermit'      },
    {'source': ['Emperor',    'Death'       ], 'result': 'Moon'        },
    {'source': ['Emperor',    'Temperance'  ], 'result': 'Hanged Man'  },
    {'source': ['Emperor',    'Star'        ], 'result': 'Justice'     },
    {'source': ['Emperor',    'Sun'         ], 'result': 'Empress'     },
    {'source': ['Emperor',    'Judgment'    ], 'result': 'Hierophant'  },
    {'source': ['Hierophant', 'Hierophant'  ], 'result': 'Hierophant'  },
    {'source': ['Hierophant', 'Lovers'      ], 'result': 'Magician'    },
    {'source': ['Hierophant', 'Chariot'     ], 'result': 'Justice'     },
    {'source': ['Hierophant', 'Justice'     ], 'result': 'Chariot'     },
    {'source': ['Hierophant', 'Hermit'      ], 'result': 'Chariot'     },
    {'source': ['Hierophant', 'Fortune'     ], 'result': 'Emperor'     },
    {'source': ['Hierophant', 'Strength'    ], 'result': 'Priestess'   },
    {'source': ['Hierophant', 'Hanged Man'  ], 'result': 'Lovers'      },
    {'source': ['Hierophant', 'Death'       ], 'result': 'Empress'     },
    {'source': ['Hierophant', 'Temperance'  ], 'result': 'Strength'    },
    {'source': ['Hierophant', 'Tower'       ], 'result': 'Temperance'  },
    {'source': ['Hierophant', 'Star'        ], 'result': 'Priestess'   },
    {'source': ['Hierophant', 'Moon'        ], 'result': 'Temperance'  },
    {'source': ['Hierophant', 'Sun'         ], 'result': 'Temperance'  },
    {'source': ['Hierophant', 'Judgment'    ], 'result': 'Lovers'      },
    {'source': ['Lovers',     'Lovers'      ], 'result': 'Lovers'      },
    {'source': ['Lovers',     'Chariot'     ], 'result': 'Emperor'     },
    {'source': ['Lovers',     'Justice'     ], 'result': 'Chariot'     },
    {'source': ['Lovers',     'Hermit'      ], 'result': 'Justice'     },
    {'source': ['Lovers',     'Fortune'     ], 'result': 'Magician'    },
    {'source': ['Lovers',     'Strength'    ], 'result': 'Hierophant'  },
    {'source': ['Lovers',     'Hanged Man'  ], 'result': 'Hermit'      },
    {'source': ['Lovers',     'Death'       ], 'result': 'Devil'       },
    {'source': ['Lovers',     'Temperance'  ], 'result': 'Priestess'   },
    {'source': ['Lovers',     'Devil'       ], 'result': 'Strength'    },
    {'source': ['Lovers',     'Tower'       ], 'result': 'Star'        },
    {'source': ['Lovers',     'Star'        ], 'result': 'Hierophant'  },
    {'source': ['Lovers',     'Moon'        ], 'result': 'Empress'     },
    {'source': ['Lovers',     'Sun'         ], 'result': 'Hierophant'  },
    {'source': ['Lovers',     'Aeon'        ], 'result': 'Hanged Man'  },
    {'source': ['Chariot',    'Chariot'     ], 'result': 'Chariot'     },
    {'source': ['Chariot',    'Justice'     ], 'result': 'Magician'    },
    {'source': ['Chariot',    'Hermit'      ], 'result': 'Temperance'  },
    {'source': ['Chariot',    'Fortune'     ], 'result': 'Strength'    },
    {'source': ['Chariot',    'Strength'    ], 'result': 'Justice'     },
    {'source': ['Chariot',    'Hanged Man'  ], 'result': 'Fortune'     },
    {'source': ['Chariot',    'Temperance'  ], 'result': 'Death'       },
    {'source': ['Chariot',    'Devil'       ], 'result': 'Hanged Man'  },
    {'source': ['Chariot',    'Tower'       ], 'result': 'Moon'        },
    {'source': ['Chariot',    'Moon'        ], 'result': 'Fortune'     },
    {'source': ['Chariot',    'Aeon'        ], 'result': 'Death'       },
    {'source': ['Justice',    'Justice'     ], 'result': 'Justice'     },
    {'source': ['Justice',    'Hermit'      ], 'result': 'Priestess'   },
    {'source': ['Justice',    'Fortune'     ], 'result': 'Chariot'     },
    {'source': ['Justice',    'Strength'    ], 'result': 'Temperance'  },
    {'source': ['Justice',    'Hanged Man'  ], 'result': 'Priestess'   },
    {'source': ['Justice',    'Death'       ], 'result': 'Moon'        },
    {'source': ['Justice',    'Temperance'  ], 'result': 'Moon'        },
    {'source': ['Justice',    'Tower'       ], 'result': 'Star'        },
    {'source': ['Justice',    'Star'        ], 'result': 'Emperor'     },
    {'source': ['Justice',    'Sun'         ], 'result': 'Emperor'     },
    {'source': ['Justice',    'Judgment'    ], 'result': 'Aeon'        },
    {'source': ['Hermit',     'Hermit'      ], 'result': 'Hermit'      },
    {'source': ['Hermit',     'Fortune'     ], 'result': 'Emperor'     },
    {'source': ['Hermit',     'Strength'    ], 'result': 'Fortune'     },
    {'source': ['Hermit',     'Hanged Man'  ], 'result': 'Fortune'     },
    {'source': ['Hermit',     'Temperance'  ], 'result': 'Hanged Man'  },
    {'source': ['Hermit',     'Devil'       ], 'result': 'Death'       },
    {'source': ['Hermit',     'Star'        ], 'result': 'Chariot'     },
    {'source': ['Hermit',     'Moon'        ], 'result': 'Magician'    },
    {'source': ['Hermit',     'Aeon'        ], 'result': 'Star'        },
    {'source': ['Fortune',    'Fortune'     ], 'result': 'Fortune'     },
    {'source': ['Fortune',    'Hanged Man'  ], 'result': 'Strength'    },
    {'source': ['Fortune',    'Temperance'  ], 'result': 'Lovers'      },
    {'source': ['Fortune',    'Devil'       ], 'result': 'Moon'        },
    {'source': ['Fortune',    'Tower'       ], 'result': 'Moon'        },
    {'source': ['Fortune',    'Star'        ], 'result': 'Moon'        },
    {'source': ['Fortune',    'Moon'        ], 'result': 'Chariot'     },
    {'source': ['Fortune',    'Sun'         ], 'result': 'Temperance'  },
    {'source': ['Fortune',    'Aeon'        ], 'result': 'Devil'       },
    {'source': ['Strength',   'Strength'    ], 'result': 'Strength'    },
    {'source': ['Strength',   'Hanged Man'  ], 'result': 'Hermit'      },
    {'source': ['Strength',   'Death'       ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Temperance'  ], 'result': 'Moon'        },
    {'source': ['Strength',   'Devil'       ], 'result': 'Fortune'     },
    {'source': ['Strength',   'Tower'       ], 'result': 'Devil'       },
    {'source': ['Strength',   'Star'        ], 'result': 'Priestess'   },
    {'source': ['Strength',   'Moon'        ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Sun'         ], 'result': 'Priestess'   },
    {'source': ['Strength',   'Judgment'    ], 'result': 'Hanged Man'  },
    {'source': ['Hanged Man', 'Hanged Man'  ], 'result': 'Hanged Man'  },
    {'source': ['Hanged Man', 'Death'       ], 'result': 'Devil'       },
    {'source': ['Hanged Man', 'Temperance'  ], 'result': 'Hierophant'  },
    {'source': ['Hanged Man', 'Devil'       ], 'result': 'Moon'        },
    {'source': ['Hanged Man', 'Tower'       ], 'result': 'Death'       },
    {'source': ['Hanged Man', 'Star'        ], 'result': 'Strength'    },
    {'source': ['Hanged Man', 'Moon'        ], 'result': 'Empress'     },
    {'source': ['Hanged Man', 'Aeon'        ], 'result': 'Temperance'  },
    {'source': ['Death',      'Death'       ], 'result': 'Death'       },
    {'source': ['Death',      'Moon'        ], 'result': 'Star'        },
    {'source': ['Temperance', 'Temperance'  ], 'result': 'Temperance'  },
    {'source': ['Temperance', 'Devil'       ], 'result': 'Death'       },
    {'source': ['Temperance', 'Tower'       ], 'result': 'Devil'       },
    {'source': ['Temperance', 'Star'        ], 'result': 'Moon'        },
    {'source': ['Temperance', 'Moon'        ], 'result': 'Empress'     },
    {'source': ['Temperance', 'Sun'         ], 'result': 'Star'        },
    {'source': ['Temperance', 'Judgment'    ], 'result': 'Moon'        },
    {'source': ['Temperance', 'Aeon'        ], 'result': 'Star'        },
    {'source': ['Devil',      'Devil'       ], 'result': 'Devil'       },
    {'source': ['Devil',      'Aeon'        ], 'result': 'Lovers'      },
    {'source': ['Tower',      'Tower'       ], 'result': 'Tower'       },
    {'source': ['Tower',      'Moon'        ], 'result': 'Fortune'     },
    {'source': ['Tower',      'Judgment'    ], 'result': 'Aeon'        },
    {'source': ['Tower',      'Aeon'        ], 'result': 'Moon'        },
    {'source': ['Star',       'Star'        ], 'result': 'Star'        },
    {'source': ['Star',       'Moon'        ], 'result': 'Death'       },
    {'source': ['Star',       'Sun'         ], 'result': 'Justice'     },
    {'source': ['Star',       'Judgment'    ], 'result': 'Temperance'  },
    {'source': ['Star',       'Aeon'        ], 'result': 'Devil'       },
    {'source': ['Moon',       'Moon'        ], 'result': 'Moon'        },
    {'source': ['Moon',       'Sun'         ], 'result': 'Temperance'  },
    {'source': ['Sun',        'Sun'         ], 'result': 'Sun'         },
    {'source': ['Sun',        'Judgment'    ], 'result': 'Star'        },
    {'source': ['Sun',        'Aeon'        ], 'result': 'Empress'     },
    {'source': ['Judgment',   'Judgment'    ], 'result': 'Judgment'    },
    {'source': ['Judgment',   'Aeon'        ], 'result': 'Star'        },
    {'source': ['Aeon',       'Aeon'        ], 'result': 'Aeon'        },
    ];

arcana3Combos = [
    {'source': ['Fool',       'Fool'        ], 'result': 'Fool'        },
    {'source': ['Fool',       'Magician'    ], 'result': 'Emperor'     },
    {'source': ['Fool',       'Priestess'   ], 'result': 'Magician'    },
    {'source': ['Fool',       'Empress'     ], 'result': 'Fortune'     },
    {'source': ['Fool',       'Emperor'     ], 'result': 'Lovers'      },
    {'source': ['Fool',       'Hierophant'  ], 'result': 'Hermit'      },
    {'source': ['Fool',       'Lovers'      ], 'result': 'Temperance'  },
    {'source': ['Fool',       'Chariot'     ], 'result': 'Devil'       },
    {'source': ['Fool',       'Justice'     ], 'result': 'Chariot'     },
    {'source': ['Fool',       'Hermit'      ], 'result': 'Priestess'   },
    {'source': ['Fool',       'Fortune'     ], 'result': 'Justice'     },
    {'source': ['Fool',       'Strength'    ], 'result': 'Hanged Man'  },
    {'source': ['Fool',       'Hanged Man'  ], 'result': 'Magician'    },
    {'source': ['Fool',       'Death'       ], 'result': 'Strength'    },
    {'source': ['Fool',       'Temperance'  ], 'result': 'Hierophant'  },
    {'source': ['Fool',       'Devil'       ], 'result': 'Justice'     },
    {'source': ['Fool',       'Tower'       ], 'result': 'Moon'        },
    {'source': ['Fool',       'Star'        ], 'result': 'Aeon'        },
    {'source': ['Fool',       'Moon'        ], 'result': 'Fortune'     },
    {'source': ['Fool',       'Sun'         ], 'result': 'Empress'     },
    {'source': ['Fool',       'Judgment'    ], 'result': 'Star'        },
    {'source': ['Fool',       'Aeon'        ], 'result': 'Death'       },
    {'source': ['Magician',   'Magician'    ], 'result': 'Magician'    },
    {'source': ['Magician',   'Priestess'   ], 'result': 'Devil'       },
    {'source': ['Magician',   'Empress'     ], 'result': 'Hanged Man'  },
    {'source': ['Magician',   'Emperor'     ], 'result': 'Lovers'      },
    {'source': ['Magician',   'Hierophant'  ], 'result': 'Hermit'      },
    {'source': ['Magician',   'Lovers'      ], 'result': 'Devil'       },
    {'source': ['Magician',   'Chariot'     ], 'result': 'Moon'        },
    {'source': ['Magician',   'Justice'     ], 'result': 'Fool'        },
    {'source': ['Magician',   'Hermit'      ], 'result': 'Hanged Man'  },
    {'source': ['Magician',   'Fortune'     ], 'result': 'Emperor'     },
    {'source': ['Magician',   'Strength'    ], 'result': 'Star'        },
    {'source': ['Magician',   'Hanged Man'  ], 'result': 'Devil'       },
    {'source': ['Magician',   'Death'       ], 'result': 'Tower'       },
    {'source': ['Magician',   'Temperance'  ], 'result': 'Death'       },
    {'source': ['Magician',   'Devil'       ], 'result': 'Temperance'  },
    {'source': ['Magician',   'Tower'       ], 'result': 'Empress'     },
    {'source': ['Magician',   'Star'        ], 'result': 'Empress'     },
    {'source': ['Magician',   'Moon'        ], 'result': 'Fortune'     },
    {'source': ['Magician',   'Sun'         ], 'result': 'Lovers'      },
    {'source': ['Magician',   'Judgment'    ], 'result': 'Tower'       },
    {'source': ['Magician',   'Aeon'        ], 'result': 'Sun'         },
    {'source': ['Priestess',  'Priestess'   ], 'result': 'Priestess'   },
    {'source': ['Priestess',  'Empress'     ], 'result': 'Lovers'      },
    {'source': ['Priestess',  'Emperor'     ], 'result': 'Hierophant'  },
    {'source': ['Priestess',  'Hierophant'  ], 'result': 'Chariot'     },
    {'source': ['Priestess',  'Lovers'      ], 'result': 'Hermit'      },
    {'source': ['Priestess',  'Chariot'     ], 'result': 'Emperor'     },
    {'source': ['Priestess',  'Justice'     ], 'result': 'Hierophant'  },
    {'source': ['Priestess',  'Hermit'      ], 'result': 'Fool'        },
    {'source': ['Priestess',  'Fortune'     ], 'result': 'Magician'    },
    {'source': ['Priestess',  'Strength'    ], 'result': 'Chariot'     },
    {'source': ['Priestess',  'Hanged Man'  ], 'result': 'Strength'    },
    {'source': ['Priestess',  'Death'       ], 'result': 'Emperor'     },
    {'source': ['Priestess',  'Temperance'  ], 'result': 'Empress'     },
    {'source': ['Priestess',  'Devil'       ], 'result': 'Tower'       },
    {'source': ['Priestess',  'Tower'       ], 'result': 'Death'       },
    {'source': ['Priestess',  'Star'        ], 'result': 'Justice'     },
    {'source': ['Priestess',  'Moon'        ], 'result': 'Star'        },
    {'source': ['Priestess',  'Sun'         ], 'result': 'Star'        },
    {'source': ['Priestess',  'Judgment'    ], 'result': 'Justice'     },
    {'source': ['Priestess',  'Aeon'        ], 'result': 'Empress'     },
    {'source': ['Empress',    'Empress'     ], 'result': 'Empress'     },
    {'source': ['Empress',    'Emperor'     ], 'result': 'Fool'        },
    {'source': ['Empress',    'Hierophant'  ], 'result': 'Priestess'   },
    {'source': ['Empress',    'Lovers'      ], 'result': 'Fortune'     },
    {'source': ['Empress',    'Chariot'     ], 'result': 'Devil'       },
    {'source': ['Empress',    'Justice'     ], 'result': 'Emperor'     },
    {'source': ['Empress',    'Hermit'      ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Fortune'     ], 'result': 'Strength'    },
    {'source': ['Empress',    'Strength'    ], 'result': 'Chariot'     },
    {'source': ['Empress',    'Hanged Man'  ], 'result': 'Chariot'     },
    {'source': ['Empress',    'Death'       ], 'result': 'Devil'       },
    {'source': ['Empress',    'Temperance'  ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Devil'       ], 'result': 'Magician'    },
    {'source': ['Empress',    'Tower'       ], 'result': 'Chariot'     },
    {'source': ['Empress',    'Star'        ], 'result': 'Temperance'  },
    {'source': ['Empress',    'Moon'        ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Sun'         ], 'result': 'Lovers'      },
    {'source': ['Empress',    'Judgment'    ], 'result': 'Devil'       },
    {'source': ['Empress',    'Aeon'        ], 'result': 'Moon'        },
    {'source': ['Emperor',    'Emperor'     ], 'result': 'Emperor'     },
    {'source': ['Emperor',    'Hierophant'  ], 'result': 'Chariot'     },
    {'source': ['Emperor',    'Lovers'      ], 'result': 'Strength'    },
    {'source': ['Emperor',    'Chariot'     ], 'result': 'Justice'     },
    {'source': ['Emperor',    'Justice'     ], 'result': 'Chariot'     },
    {'source': ['Emperor',    'Hermit'      ], 'result': 'Lovers'      },
    {'source': ['Emperor',    'Fortune'     ], 'result': 'Sun'         },
    {'source': ['Emperor',    'Strength'    ], 'result': 'Hanged Man'  },
    {'source': ['Emperor',    'Hanged Man'  ], 'result': 'Temperance'  },
    {'source': ['Emperor',    'Death'       ], 'result': 'Moon'        },
    {'source': ['Emperor',    'Temperance'  ], 'result': 'Hanged Man'  },
    {'source': ['Emperor',    'Devil'       ], 'result': 'Tower'       },
    {'source': ['Emperor',    'Tower'       ], 'result': 'Death'       },
    {'source': ['Emperor',    'Star'        ], 'result': 'Hermit'      },
    {'source': ['Emperor',    'Moon'        ], 'result': 'Tower'       },
    {'source': ['Emperor',    'Sun'         ], 'result': 'Empress'     },
    {'source': ['Emperor',    'Judgment'    ], 'result': 'Hierophant'  },
    {'source': ['Emperor',    'Aeon'        ], 'result': 'Sun'         },
    {'source': ['Hierophant', 'Hierophant'  ], 'result': 'Hierophant'  },
    {'source': ['Hierophant', 'Lovers'      ], 'result': 'Temperance'  },
    {'source': ['Hierophant', 'Chariot'     ], 'result': 'Sun'         },
    {'source': ['Hierophant', 'Justice'     ], 'result': 'Magician'    },
    {'source': ['Hierophant', 'Hermit'      ], 'result': 'Chariot'     },
    {'source': ['Hierophant', 'Fortune'     ], 'result': 'Emperor'     },
    {'source': ['Hierophant', 'Strength'    ], 'result': 'Emperor'     },
    {'source': ['Hierophant', 'Hanged Man'  ], 'result': 'Fortune'     },
    {'source': ['Hierophant', 'Death'       ], 'result': 'Empress'     },
    {'source': ['Hierophant', 'Temperance'  ], 'result': 'Strength'    },
    {'source': ['Hierophant', 'Devil'       ], 'result': 'Fool'        },
    {'source': ['Hierophant', 'Tower'       ], 'result': 'Temperance'  },
    {'source': ['Hierophant', 'Star'        ], 'result': 'Priestess'   },
    {'source': ['Hierophant', 'Moon'        ], 'result': 'Temperance'  },
    {'source': ['Hierophant', 'Sun'         ], 'result': 'Temperance'  },
    {'source': ['Hierophant', 'Judgment'    ], 'result': 'Lovers'      },
    {'source': ['Hierophant', 'Aeon'        ], 'result': 'Tower'       },
    {'source': ['Lovers',     'Lovers'      ], 'result': 'Lovers'      },
    {'source': ['Lovers',     'Chariot'     ], 'result': 'Strength'    },
    {'source': ['Lovers',     'Justice'     ], 'result': 'Hanged Man'  },
    {'source': ['Lovers',     'Hermit'      ], 'result': 'Hierophant'  },
    {'source': ['Lovers',     'Fortune'     ], 'result': 'Fool'        },
    {'source': ['Lovers',     'Strength'    ], 'result': 'Hierophant'  },
    {'source': ['Lovers',     'Hanged Man'  ], 'result': 'Hermit'      },
    {'source': ['Lovers',     'Death'       ], 'result': 'Devil'       },
    {'source': ['Lovers',     'Temperance'  ], 'result': 'Priestess'   },
    {'source': ['Lovers',     'Devil'       ], 'result': 'Death'       },
    {'source': ['Lovers',     'Tower'       ], 'result': 'Star'        },
    {'source': ['Lovers',     'Star'        ], 'result': 'Hierophant'  },
    {'source': ['Lovers',     'Moon'        ], 'result': 'Empress'     },
    {'source': ['Lovers',     'Sun'         ], 'result': 'Hierophant'  },
    {'source': ['Lovers',     'Judgment'    ], 'result': 'Sun'         },
    {'source': ['Lovers',     'Aeon'        ], 'result': 'Hanged Man'  },
    {'source': ['Chariot',    'Chariot'     ], 'result': 'Chariot'     },
    {'source': ['Chariot',    'Justice'     ], 'result': 'Magician'    },
    {'source': ['Chariot',    'Hermit'      ], 'result': 'Hanged Man'  },
    {'source': ['Chariot',    'Fortune'     ], 'result': 'Hermit'      },
    {'source': ['Chariot',    'Strength'    ], 'result': 'Justice'     },
    {'source': ['Chariot',    'Hanged Man'  ], 'result': 'Fortune'     },
    {'source': ['Chariot',    'Death'       ], 'result': 'Fool'        },
    {'source': ['Chariot',    'Temperance'  ], 'result': 'Death'       },
    {'source': ['Chariot',    'Devil'       ], 'result': 'Star'        },
    {'source': ['Chariot',    'Tower'       ], 'result': 'Moon'        },
    {'source': ['Chariot',    'Star'        ], 'result': 'Sun'         },
    {'source': ['Chariot',    'Moon'        ], 'result': 'Fortune'     },
    {'source': ['Chariot',    'Sun'         ], 'result': 'Justice'     },
    {'source': ['Chariot',    'Judgment'    ], 'result': 'Tower'       },
    {'source': ['Chariot',    'Aeon'        ], 'result': 'Death'       },
    {'source': ['Justice',    'Justice'     ], 'result': 'Justice'     },
    {'source': ['Justice',    'Hermit'      ], 'result': 'Strength'    },
    {'source': ['Justice',    'Fortune'     ], 'result': 'Chariot'     },
    {'source': ['Justice',    'Strength'    ], 'result': 'Temperance'  },
    {'source': ['Justice',    'Hanged Man'  ], 'result': 'Priestess'   },
    {'source': ['Justice',    'Death'       ], 'result': 'Moon'        },
    {'source': ['Justice',    'Temperance'  ], 'result': 'Moon'        },
    {'source': ['Justice',    'Devil'       ], 'result': 'Tower'       },
    {'source': ['Justice',    'Tower'       ], 'result': 'Sun'         },
    {'source': ['Justice',    'Star'        ], 'result': 'Emperor'     },
    {'source': ['Justice',    'Moon'        ], 'result': 'Tower'       },
    {'source': ['Justice',    'Sun'         ], 'result': 'Emperor'     },
    {'source': ['Justice',    'Judgment'    ], 'result': 'Aeon'        },
    {'source': ['Justice',    'Aeon'        ], 'result': 'Judgment'    },
    {'source': ['Hermit',     'Hermit'      ], 'result': 'Hermit'      },
    {'source': ['Hermit',     'Fortune'     ], 'result': 'Emperor'     },
    {'source': ['Hermit',     'Strength'    ], 'result': 'Fortune'     },
    {'source': ['Hermit',     'Hanged Man'  ], 'result': 'Fortune'     },
    {'source': ['Hermit',     'Death'       ], 'result': 'Tower'       },
    {'source': ['Hermit',     'Temperance'  ], 'result': 'Hanged Man'  },
    {'source': ['Hermit',     'Devil'       ], 'result': 'Death'       },
    {'source': ['Hermit',     'Tower'       ], 'result': 'Death'       },
    {'source': ['Hermit',     'Star'        ], 'result': 'Chariot'     },
    {'source': ['Hermit',     'Moon'        ], 'result': 'Magician'    },
    {'source': ['Hermit',     'Sun'         ], 'result': 'Star'        },
    {'source': ['Hermit',     'Judgment'    ], 'result': 'Tower'       },
    {'source': ['Hermit',     'Aeon'        ], 'result': 'Star'        },
    {'source': ['Fortune',    'Fortune'     ], 'result': 'Fortune'     },
    {'source': ['Fortune',    'Strength'    ], 'result': 'Sun'         },
    {'source': ['Fortune',    'Hanged Man'  ], 'result': 'Strength'    },
    {'source': ['Fortune',    'Death'       ], 'result': 'Judgment'    },
    {'source': ['Fortune',    'Temperance'  ], 'result': 'Lovers'      },
    {'source': ['Fortune',    'Devil'       ], 'result': 'Hermit'      },
    {'source': ['Fortune',    'Tower'       ], 'result': 'Aeon'        },
    {'source': ['Fortune',    'Star'        ], 'result': 'Moon'        },
    {'source': ['Fortune',    'Moon'        ], 'result': 'Chariot'     },
    {'source': ['Fortune',    'Sun'         ], 'result': 'Temperance'  },
    {'source': ['Fortune',    'Judgment'    ], 'result': 'Star'        },
    {'source': ['Fortune',    'Aeon'        ], 'result': 'Devil'       },
    {'source': ['Strength',   'Hermit'      ], 'result': 'Emperor'     },
    {'source': ['Strength',   'Strength'    ], 'result': 'Strength'    },
    {'source': ['Strength',   'Hanged Man'  ], 'result': 'Fortune'     },
    {'source': ['Strength',   'Death'       ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Temperance'  ], 'result': 'Moon'        },
    {'source': ['Strength',   'Devil'       ], 'result': 'Empress'     },
    {'source': ['Strength',   'Tower'       ], 'result': 'Judgment'    },
    {'source': ['Strength',   'Star'        ], 'result': 'Priestess'   },
    {'source': ['Strength',   'Moon'        ], 'result': 'Aeon'        },
    {'source': ['Strength',   'Sun'         ], 'result': 'Priestess'   },
    {'source': ['Strength',   'Judgment'    ], 'result': 'Hanged Man'  },
    {'source': ['Strength',   'Aeon'        ], 'result': 'Tower'       },
    {'source': ['Hanged Man', 'Hanged Man'  ], 'result': 'Hanged Man'  },
    {'source': ['Hanged Man', 'Death'       ], 'result': 'Devil'       },
    {'source': ['Hanged Man', 'Temperance'  ], 'result': 'Hierophant'  },
    {'source': ['Hanged Man', 'Devil'       ], 'result': 'Death'       },
    {'source': ['Hanged Man', 'Tower'       ], 'result': 'Death'       },
    {'source': ['Hanged Man', 'Star'        ], 'result': 'Strength'    },
    {'source': ['Hanged Man', 'Moon'        ], 'result': 'Empress'     },
    {'source': ['Hanged Man', 'Sun'         ], 'result': 'Judgment'    },
    {'source': ['Hanged Man', 'Judgment'    ], 'result': 'Aeon'        },
    {'source': ['Hanged Man', 'Aeon'        ], 'result': 'Temperance'  },
    {'source': ['Death',      'Chariot'     ], 'result': 'Judgment'    },
    {'source': ['Death',      'Death'       ], 'result': 'Death'       },
    {'source': ['Death',      'Temperance'  ], 'result': 'Tower'       },
    {'source': ['Death',      'Devil'       ], 'result': 'Judgment'    },
    {'source': ['Death',      'Tower'       ], 'result': 'Sun'         },
    {'source': ['Death',      'Star'        ], 'result': 'Tower'       },
    {'source': ['Death',      'Moon'        ], 'result': 'Star'        },
    {'source': ['Death',      'Sun'         ], 'result': 'Moon'        },
    {'source': ['Death',      'Judgment'    ], 'result': 'Fool'        },
    {'source': ['Death',      'Aeon'        ], 'result': 'Sun'         },
    {'source': ['Temperance', 'Temperance'  ], 'result': 'Temperance'  },
    {'source': ['Temperance', 'Devil'       ], 'result': 'Moon'        },
    {'source': ['Temperance', 'Tower'       ], 'result': 'Devil'       },
    {'source': ['Temperance', 'Star'        ], 'result': 'Hermit'      },
    {'source': ['Temperance', 'Moon'        ], 'result': 'Empress'     },
    {'source': ['Temperance', 'Sun'         ], 'result': 'Judgment'    },
    {'source': ['Temperance', 'Judgment'    ], 'result': 'Justice'     },
    {'source': ['Temperance', 'Aeon'        ], 'result': 'Star'        },
    {'source': ['Devil',      'Devil'       ], 'result': 'Devil'       },
    {'source': ['Devil',      'Tower'       ], 'result': 'Judgment'    },
    {'source': ['Devil',      'Star'        ], 'result': 'Magician'    },
    {'source': ['Devil',      'Moon'        ], 'result': 'Judgment'    },
    {'source': ['Devil',      'Sun'         ], 'result': 'Death'       },
    {'source': ['Devil',      'Judgment'    ], 'result': 'Moon'        },
    {'source': ['Devil',      'Aeon'        ], 'result': 'Lovers'      },
    {'source': ['Tower',      'Tower'       ], 'result': 'Tower'       },
    {'source': ['Tower',      'Star'        ], 'result': 'Judgment'    },
    {'source': ['Tower',      'Moon'        ], 'result': 'Fortune'     },
    {'source': ['Tower',      'Sun'         ], 'result': 'Moon'        },
    {'source': ['Tower',      'Judgment'    ], 'result': 'Aeon'        },
    {'source': ['Tower',      'Aeon'        ], 'result': 'Fool'        },
    {'source': ['Star',       'Star'        ], 'result': 'Star'        },
    {'source': ['Star',       'Moon'        ], 'result': 'Sun'         },
    {'source': ['Star',       'Sun'         ], 'result': 'Aeon'        },
    {'source': ['Star',       'Judgment'    ], 'result': 'Temperance'  },
    {'source': ['Star',       'Aeon'        ], 'result': 'Devil'       },
    {'source': ['Moon',       'Moon'        ], 'result': 'Moon'        },
    {'source': ['Moon',       'Sun'         ], 'result': 'Temperance'  },
    {'source': ['Moon',       'Judgment'    ], 'result': 'Priestess'   },
    {'source': ['Moon',       'Aeon'        ], 'result': 'Judgment'    },
    {'source': ['Sun',        'Sun'         ], 'result': 'Sun'         },
    {'source': ['Sun',        'Judgment'    ], 'result': 'Star'        },
    {'source': ['Sun',        'Aeon'        ], 'result': 'Empress'     },
    {'source': ['Judgment',   'Judgment'    ], 'result': 'Judgment'    },
    {'source': ['Judgment',   'Aeon'        ], 'result': 'Fool'        },
    {'source': ['Aeon',       'Aeon'        ], 'result': 'Aeon'        },
]

specialCombos = [
    {'result': 'Alice', 'sources': ['Pixie', 'Lilim', 'Narcissus', 'Nata Taishi']},
    {'result': 'Arahabaki', 'sources': ['Omoikane', 'Take-minakata', 'Okuninushi', 'Kikuri-hime']},
    {'result': 'Asura', 'sources': ['Yatagarasu', 'Quetzalcoatl', 'Jatayu', 'Horus', 'Suparna', 'Vishnu']},
    {'result': 'Attis', 'sources': ['Inugami', 'Take-minakata', 'Orthrus', 'Vasuki', 'Ubelluris']},
    {'result': 'Beelzebub', 'sources': ['Incubus', 'Succubus', 'Pazuzu', 'Lilith', 'Abaddon', 'Baal Zebul']},
    {'result': 'Black Frost', 'sources': ['Jack Frost', 'Pyro Jack', 'King Frost', 'Queen Mab']},
    {'result': 'Daisoujou', 'sources': ['Mithra', 'Ara Mitama', 'Nigi Mitama', 'Kusi Mitama', 'Saki Mitama']},
    {'result': 'Girimehkala', 'sources': ['Gurr', 'Vetala', 'Taraka', 'Rangda']},
    {'result': 'Kohryu', 'sources': ['Genbu', 'Seiryuu', 'Suzaku', 'Byakko']},
    {'result': 'Lilith', 'sources': ['Lilim', 'Vetala', 'Incubus', 'Succubus']},
    {'result': 'Lucifer', 'sources': ['Samael', 'Abaddon', 'Beelzebub', 'Satan', 'Helel']},
    {'result': 'Mara', 'sources': ['Incubus', 'Pazuzu', 'Mot', 'Kumbhanda', 'Attis']},
    {'result': 'Masakado', 'sources': ['Zouchouten', 'Jikokuten', 'Koumokuten', 'Bishamonten']},
    {'result': 'Messiah', 'sources': ['Orpheus', 'Thanatos']},
    {'result': 'Metatron', 'sources': ['Uriel', 'Raphael', 'Gabriel', 'Michael']},
    {'result': 'Norn', 'sources': ['Clotho', 'Lachesis', 'Atropos']},
    {'result': 'Orpheus', 'sources': ['Slime', 'Legion']},
    {'result': 'Orpheus Telos', 'sources': ['Thanatos', 'Chi You', 'Helel', 'Asura', 'Messiah', 'Metatron']},
    {'result': 'Sandalphon', 'sources': ['Gurr', 'Suzaku', 'Yatagarasu', 'Horus', 'Garuda']},
    {'result': 'Shiva', 'sources': ['Barong', 'Rangda']},
    {'result': 'Susano-o', 'sources': ['Orpheus', 'Legion', 'Black Frost', 'Ose', 'Decarabia', 'Loki']},
    {'result': 'Thanatos', 'sources': ['Ghoul', 'Pale Rider', 'Loa', 'Samael', 'Mot', 'Alice']},
]

from collections import defaultdict
fusion2_arcana = defaultdict(dict)
fusion3_arcana = defaultdict(dict)

for combo in arcana2Combos:
  a,b = combo['source']
  res = combo['result']
  try:
    if len(fusion2_arcana[a][b]) > 0:
      print "already had this in 2?", a, b, res, fusion2_arcana[a][b]
    if len(fusion2_arcana[b][a]) > 0:
      print "already had this in 2?", a, b, res, fusion2_arcana[b][a]
  except KeyError:
    pass
  fusion2_arcana[a][b] = res
  fusion2_arcana[b][a] = res

for combo in arcana3Combos:
  a,b = combo['source']
  res = combo['result']
  try:
    if len(fusion3_arcana[a][b]) > 0:
      print "already had this in 3?", a, b, res, fusion3_arcana[a][b]
  except KeyError:
    pass
  fusion3_arcana[a][b] = res

#don't really like pprint's format so whatever do it myself
with open('fusions.txt', 'w') as f:
  f.write("fusion2_arcana = {\n")
  for k,v in fusion2_arcana.iteritems():
    f.write("  '%s' : %s\n" % (k, repr(v)))
  f.write("}\n\nfusion3_arcana = {\n")
  for k,v in fusion3_arcana.iteritems():
    f.write("  '%s' : %s\n" % (k, repr(v)))
  f.write("}\n")

